version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: sportif-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sportif-net

  backend:
    build: ./backend
    container_name: sportif-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sportif-tn
      - JWT_SECRET=sportif_tn_super_secret_2026
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - sportif-net

  frontend:
    build: ./frontend
    container_name: sportif-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sportif-net

volumes:
  mongo-data:

networks:
  sportif-net:
    driver: bridge
