version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: sportify-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sportify-net

  backend:
    build: ./backend
    container_name: sportify-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://rihabcherni000_db_user:xPBpXhfbvOYzINWS@cluster0.lgeg4iq.mongodb.net/
      - JWT_SECRET=sportify_super_secret_2026
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - sportify-net

  frontend:
    build: ./frontend
    container_name: sportify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sportify-net

volumes:
  mongo-data:

networks:
  sportify-net:
    driver: bridge
